export const EFOOTBALL_SKILLS = [
    { name: "Scissors Feint", description: "Performs a faster Scissors Feint when the command is input." },
    { name: "Double Touch", description: "Performs a quicker Double Touch than normal after the command." },
    { name: "Flip Flap", description: "Executes a Flip Flap when the command is entered." },
    { name: "Marseille Turn", description: "Performs a faster Marseille Turn upon command." },
    { name: "Sombrero", description: "Triggers a Sombrero Turn or Flick Turn when trapping, based on the situation, and improves Flick accuracy." },
    { name: "Chop Turn", description: "Performs a quicker Chop Turn when commanded." },
    { name: "Cut Behind & Turn", description: "Performs a Cut Behind; at wider angles, also uses a special trapping motion." },
    { name: "Scotch Move", description: "Executes a Scotch Move on command." },
    { name: "Sole Control", description: "Improves ball control using the soles of the feet when executing feints and turns." },
    { name: "Momentum Dribbling", description: "Boosts dribbling effectiveness in the attacking third (deep in opposition territory)." },
    { name: "Acceleration Burst", description: "Enables a quick Sharp Touch when stationary or moving slowly; special Sharp Touch motions may also trigger." },
    { name: "Heading", description: "Improves heading accuracy and increases the frequency of downward headers." },
    { name: "Bullet Header", description: "Drives headers sharply toward goal with power and accuracy, even from awkward positions or off-balance." },
    { name: "Long-range Curler", description: "Performs an accurate Controlled Shot with heavy curl, effective even from distance." },
    { name: "Blitz Curler", description: "Performs a Controlled Shot with strong topspin while the Power Gauge is at least 50% full." },
    { name: "Chip Shot Control", description: "Performs accurate chip shots, even at higher running speeds." },
    { name: "Knuckle Shot", description: "Performs a Knuckle Shot on Stunning Shot input when the Power Gauge is 50–65% full; a strong free-kick option." },
    { name: "Dipping Shot", description: "Performs a dipping Stunning Shot when the Power Gauge is 20–50% full." },
    { name: "Rising Shot", description: "Performs a rising Stunning Shot when the Power Gauge is 65–95% full." },
    { name: "Long-range Shooting", description: "Improves accuracy on shots taken from outside the box." },
    { name: "Acrobatic Finishing", description: "Enables finishes from awkward body positions or when off-balance." },
    { name: "Heel Trick", description: "Allows passes and shots using the heel, even from awkward positions or when off-balance." },
    { name: "First-time Shot", description: "Improves technique and precision on first-time finishes." },
    { name: "Phenomenal Finishing", description: "Increases the power and accuracy of finishes attempted from unorthodox body positions." },
    { name: "One-touch Pass", description: "Improves technique and precision on one-touch passes." },
    { name: "Through Passing", description: "Enables accurate through passes with appropriate trajectory and improves overall through-ball accuracy." },
    { name: "Weighted Pass", description: "Performs accurate Lofted Passes or chipped through balls with heavy backspin to a forward area." },
    { name: "Pinpoint Crossing", description: "Delivers sharp, accurate crosses with significant curl." },
    { name: "Edged Crossing", description: "Enables vertically rotating (dipping) crosses that drop sharply." },
    { name: "Outside Curler", description: "Performs precise shots or passes with the outside of the boot—even from range—using the stronger foot for accuracy." },
    { name: "Rabona", description: "Performs a Rabona to disrupt the defence’s timing with a surprise kick, using the stronger foot for accuracy." },
    { name: "No Look Pass", description: "Enables unexpected passes that mislead opponents’ line of sight." },
    { name: "Game-changing Pass", description: "Improves passing performance after second-half kick-off when the team is drawing or behind." },
    { name: "Visionary Pass", description: "Increases the accuracy of recipients’ one-touch passes, first-time shots, and traps from this player’s passes." },
    { name: "Phenomenal Pass", description: "Boosts power and accuracy of passes attempted from unorthodox body positions." },
    { name: "Low Lofted Pass", description: "Enables long, accurate Lofted Passes with a low trajectory." },
    { name: "GK Low Punt", description: "Enables accurate punt kicks with a low trajectory." },
    { name: "GK High Punt", description: "Enables long, high punts that travel deep into opposition territory." },
    { name: "Long Throw", description: "Improves outfield players’ long throw-in distance." },
    { name: "GK Long Throw", description: "Improves a goalkeeper’s throwing range." },
    { name: "Penalty Specialist", description: "Enables higher-accuracy penalty kicks." },
    { name: "GK Penalty Saver", description: "Improves goalkeeping reactions against penalties." },
    { name: "GK Directing Defence", description: "Goalkeeper skill that boosts the defensive ability of teammates positioned deep in your own half." },
    { name: "Gamesmanship", description: "Wins fouls more easily while in possession." },
    { name: "Man Marking", description: "React quickly to an opponent’s movements and apply tight, persistent marking." },
    { name: "Track Back", description: "Aggressively applies pressure to the ball carrier all the way from the front line." },
    { name: "Interception", description: "Improves the ability to read play and cut out passes." },
    { name: "Blocker", description: "Raises the chance of blocking shots and passes." },
    { name: "Aerial Superiority", description: "Improves success rate in aerial duels." },
    { name: "Sliding Tackle", description: "Increases success when winning the ball via sliding tackles." },
    { name: "Acrobatic Clearance", description: "Enables acrobatic clearances with the feet from difficult positions." },
    { name: "Captaincy", description: "Leads the team on the pitch, helping reduce fatigue effects for teammates." },
    { name: "Super-sub", description: "Boosts abilities when introduced in the second half." },
    { name: "Fighting Spirit", description: "Improves performance under pressure, fatigue, and adversity." }
];

export const getSkillDescription = (skillName) => {
    if (!skillName) return "";
    const found = EFOOTBALL_SKILLS.find(
        s => s.name.toLowerCase() === skillName.trim().toLowerCase()
    );
    return found ? found.description : "Special player skill.";
};
